version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./apiGateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - service-rest1
      - service-rest2

  # Service REST 1
  service-rest1:
    build: ./serviceRest1
    ports:
      - "8081:8080"
    networks:
      - microservices-network

  # Service REST 2
  service-rest2:
    build: ./serviceRest2
    ports:
      - "8082:8080"
    networks:
      - microservices-network

  # Client 1
  client1:
    build: ./client1
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - api-gateway

  # Client 2
  client2:
    build: ./client2
    ports:
      - "3001:3000"
    networks:
      - microservices-network
    depends_on:
      - api-gateway

networks:
  microservices-network:
    driver: bridge 