version: '3.8'

services:
  # Service REST 1
  service-rest1:
    build: ./serviceRest1
    ports:
      - "8081:8080"
    networks:
      - microservices-network
    depends_on:
      - mysql-db
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/133-db-alparslanc
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: emf123
      MYSQL_DATABASE: 133-db-alparslanc
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network
    command: --default-authentication-plugin=mysql_native_password
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ajouter cette ligne pour permettre la connexion depuis l'hôte

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data:
