version: '3.8'

services:
  # Service REST 1
  service-rest1:
    build: ./serviceRest1
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_APPLICATION_NAME=service1
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3308/133-db-alparslanc
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - backend

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: emf123
      MYSQL_DATABASE: 133-db-alparslanc
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
