-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 13:07:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 133-db-valleliant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 133-db-valleliant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `133-db-valleliant` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema 133-db-alparslanc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 133-db-alparslanc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `133-db-alparslanc` DEFAULT CHARACTER SET utf8mb3 ;
USE `133-db-valleliant` ;

-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_admin` (
  `pk_admin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_admin`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_games` (
  `pk_games` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_games`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_tournaments` (
  `pk_tournaments` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `fk_game` INT NOT NULL,
  `fk_admin` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`pk_tournaments`, `fk_game`, `fk_admin`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_t_tournaments_t_admin1_idx` (`fk_admin` ASC) VISIBLE,
  INDEX `fk_t_tournaments_t_games1_idx` (`fk_game` ASC) VISIBLE,
  CONSTRAINT `fk_t_tournaments_t_admin1`
    FOREIGN KEY (`fk_admin`)
    REFERENCES `133-db-valleliant`.`t_admin` (`pk_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tournaments_t_games1`
    FOREIGN KEY (`fk_game`)
    REFERENCES `133-db-valleliant`.`t_games` (`pk_games`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_teams` (
  `pk_teams` INT NOT NULL AUTO_INCREMENT,
  `fk_tournament` INT NOT NULL,
  PRIMARY KEY (`pk_teams`, `fk_tournament`),
  INDEX `fk_t_teams_t_tournaments1_idx` (`fk_tournament` ASC) VISIBLE,
  CONSTRAINT `fk_t_teams_t_tournaments1`
    FOREIGN KEY (`fk_tournament`)
    REFERENCES `133-db-valleliant`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_matches` (
  `pk_matches` INT NOT NULL AUTO_INCREMENT,
  `fk_tournaments` INT NOT NULL,
  `fk_team1` INT NOT NULL,
  `fk_team2` INT NOT NULL,
  `score1` VARCHAR(45) NULL,
  `score2` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`pk_matches`, `fk_tournaments`, `fk_team1`, `fk_team2`),
  INDEX `fk_t_matches_t_teams_idx` (`fk_team1` ASC) VISIBLE,
  INDEX `fk_t_matches_t_teams1_idx` (`fk_team2` ASC) VISIBLE,
  INDEX `fk_t_matches_t_tournaments1_idx` (`fk_tournaments` ASC) VISIBLE,
  CONSTRAINT `fk_t_matches_t_teams`
    FOREIGN KEY (`fk_team1`)
    REFERENCES `133-db-valleliant`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_matches_t_teams1`
    FOREIGN KEY (`fk_team2`)
    REFERENCES `133-db-valleliant`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_matches_t_tournaments1`
    FOREIGN KEY (`fk_tournaments`)
    REFERENCES `133-db-valleliant`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`t_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`t_ranking` (
  `pk_ranking` INT NOT NULL AUTO_INCREMENT,
  `fk_tournaments` INT NOT NULL,
  PRIMARY KEY (`pk_ranking`, `fk_tournaments`),
  INDEX `fk_t_ranking_t_tournaments1_idx` (`fk_tournaments` ASC) VISIBLE,
  CONSTRAINT `fk_t_ranking_t_tournaments1`
    FOREIGN KEY (`fk_tournaments`)
    REFERENCES `133-db-valleliant`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-valleliant`.`tr_teams_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-valleliant`.`tr_teams_ranking` (
  `pfk_teams_ranking` INT NOT NULL AUTO_INCREMENT,
  `fk_teams` INT NOT NULL,
  `fk_ranking` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`pfk_teams_ranking`, `fk_teams`, `fk_ranking`),
  INDEX `fk_t_teams_has_t_ranking_t_ranking1_idx` (`fk_ranking` ASC) VISIBLE,
  INDEX `fk_t_teams_has_t_ranking_t_teams1_idx` (`fk_teams` ASC) VISIBLE,
  CONSTRAINT `fk_t_teams_has_t_ranking_t_teams1`
    FOREIGN KEY (`fk_teams`)
    REFERENCES `133-db-valleliant`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_teams_has_t_ranking_t_ranking1`
    FOREIGN KEY (`fk_ranking`)
    REFERENCES `133-db-valleliant`.`t_ranking` (`pk_ranking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `133-db-alparslanc` ;

-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_tournaments` (
  `pk_tournaments` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pk_tournaments`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_user` (
  `pk_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pk_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_teams` (
  `pk_teams` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `fk_capitaine` INT NOT NULL,
  `fk_tournaments` INT NOT NULL,
  PRIMARY KEY (`pk_teams`, `fk_capitaine`, `fk_tournaments`),
  INDEX `fk_t_teams_t_user_idx` (`fk_capitaine` ASC) VISIBLE,
  INDEX `fk_t_teams_t_tournaments1_idx` (`fk_tournaments` ASC) VISIBLE,
  CONSTRAINT `fk_t_teams_t_user`
    FOREIGN KEY (`fk_capitaine`)
    REFERENCES `133-db-alparslanc`.`t_user` (`pk_user`),
  CONSTRAINT `fk_t_teams_t_tournaments1`
    FOREIGN KEY (`fk_tournaments`)
    REFERENCES `133-db-alparslanc`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_matches` (
  `pk_matches` INT NOT NULL AUTO_INCREMENT,
  `fk_tournaments` INT NOT NULL,
  `fk_team1` INT NOT NULL,
  `fk_teams2` INT NOT NULL,
  PRIMARY KEY (`pk_matches`, `fk_tournaments`, `fk_team1`, `fk_teams2`),
  INDEX `fk_t_matches_t_tournaments1_idx` (`fk_tournaments` ASC) VISIBLE,
  INDEX `fk_t_matches_t_teams1_idx` (`fk_team1` ASC) VISIBLE,
  INDEX `fk_t_matches_t_teams2_idx` (`fk_teams2` ASC) VISIBLE,
  CONSTRAINT `fk_t_matches_t_tournaments1`
    FOREIGN KEY (`fk_tournaments`)
    REFERENCES `133-db-alparslanc`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_matches_t_teams1`
    FOREIGN KEY (`fk_team1`)
    REFERENCES `133-db-alparslanc`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_matches_t_teams2`
    FOREIGN KEY (`fk_teams2`)
    REFERENCES `133-db-alparslanc`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`tr_team_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`tr_team_user` (
  `pfk_team_user` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NOT NULL,
  `fk_teams` INT NOT NULL,
  PRIMARY KEY (`pfk_team_user`, `fk_user`, `fk_teams`),
  INDEX `fk_pfk_team_user_t_user1_idx` (`fk_user` ASC) VISIBLE,
  INDEX `fk_pfk_team_user_t_teams1_idx` (`fk_teams` ASC) VISIBLE,
  CONSTRAINT `fk_pfk_team_user_t_teams1`
    FOREIGN KEY (`fk_teams`)
    REFERENCES `133-db-alparslanc`.`t_teams` (`pk_teams`),
  CONSTRAINT `fk_pfk_team_user_t_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `133-db-alparslanc`.`t_user` (`pk_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_ranking` (
  `pk_ranking` INT NOT NULL AUTO_INCREMENT,
  `fk_tournaments` INT NOT NULL,
  PRIMARY KEY (`pk_ranking`, `fk_tournaments`),
  INDEX `fk_t_ranking_t_tournaments1_idx` (`fk_tournaments` ASC) VISIBLE,
  CONSTRAINT `fk_t_ranking_t_tournaments1`
    FOREIGN KEY (`fk_tournaments`)
    REFERENCES `133-db-alparslanc`.`t_tournaments` (`pk_tournaments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `133-db-alparslanc`.`t_teams_has_t_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `133-db-alparslanc`.`t_teams_has_t_ranking` (
  `pfk_teams_ranking` INT NOT NULL AUTO_INCREMENT,
  `t_teams_pk_teams` INT NOT NULL,
  `t_ranking_pk_ranking` INT NOT NULL,
  PRIMARY KEY (`pfk_teams_ranking`, `t_teams_pk_teams`, `t_ranking_pk_ranking`),
  INDEX `fk_t_teams_has_t_ranking_t_ranking1_idx` (`t_ranking_pk_ranking` ASC) VISIBLE,
  INDEX `fk_t_teams_has_t_ranking_t_teams1_idx` (`t_teams_pk_teams` ASC) VISIBLE,
  CONSTRAINT `fk_t_teams_has_t_ranking_t_teams1`
    FOREIGN KEY (`t_teams_pk_teams`)
    REFERENCES `133-db-alparslanc`.`t_teams` (`pk_teams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_teams_has_t_ranking_t_ranking1`
    FOREIGN KEY (`t_ranking_pk_ranking`)
    REFERENCES `133-db-alparslanc`.`t_ranking` (`pk_ranking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
