FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ENV DATABASE_URL=jdbc:mysql://host.docker.internal:3306/bd_kitzbuehl
COPY target/ex7-0.0.1-SNAPSHOT.jar ex7.jar
EXPOSE 8080
ENTRYPOINT exec java $JAVA_OPTS -jar ex7.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar ex7.jar
